### ISSUE TITLE
How to enable experimental features? 

### ISSUE THREAD

**Issue by renepickhardt** [ElementsProject/secp256k1-zkp#76]
The readme should reference that experimental features can be enabled for example via 

```
./configure --enable-experimental --enable-module-schnorrsig --enable-module-musig
```

or more general `./configure --help`

**Comment by real-or-random** [comment]
Yeah, so this is a "standard" autotools library, so `./configure --help` is generally the way to go, and yeah, it can't be wrong to mention that in the README. (I don't think we need more in the README, the configure help then shows everything you need.)

I'm closing this here but only because this should be fixed upstream in https://github.com/bitcoin-core/secp256k1. Feel free to open an issue (or directly a PR) there.

**Comment by jonasnick** [comment]
I think it would makes sense to list the available modules in the README, point to the module doc (include file and `.md` if available)  and examples and also give a hint about how to enable them.
